# Generated by Django 3.2.20 on 2023-10-15 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpurchase',
            name='first_purchase_made',
            field=models.BooleanField(default=False),
        ),
    ]
